# Generated by Django 5.2.5 on 2025-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_created_at_patient_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
