# Generated by Django 5.0.7 on 2025-07-14 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreOpAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('surgeon', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('operation', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_operation', models.DateField(auto_now_add=True)),
                ('operation_reason', models.TextField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('recently_unwell', models.TextField(blank=True, default='')),
                ('previous_anaesthetic', models.TextField(blank=True, default='')),
                ('family_anaesthetic_reaction', models.TextField(blank=True, default='')),
                ('allergies', models.TextField(blank=True, default='')),
                ('regular_medications', models.TextField(blank=True, default='')),
                ('smoke_or_vape', models.CharField(blank=True, max_length=10, null=True)),
                ('alcohol_consumption', models.TextField(blank=True, default='')),
                ('heart_issues', models.TextField(blank=True, default='')),
                ('shortness_of_breath', models.TextField(blank=True, default='')),
                ('lung_issues', models.TextField(blank=True, default='')),
                ('diabetes', models.TextField(blank=True, default='')),
                ('gastrointestinal_issues', models.TextField(blank=True, default='')),
                ('thyroid_disease', models.TextField(blank=True, default='')),
                ('neurological_condition', models.TextField(blank=True, default='')),
                ('rheumatoid_arthritis', models.TextField(blank=True, default='')),
                ('kidney_condition', models.TextField(blank=True, default='')),
                ('blood_clotting', models.TextField(blank=True, default='')),
                ('cancer', models.TextField(blank=True, default='')),
                ('covid_history', models.TextField(blank=True, default='')),
                ('dental_descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('effective_pain_relievers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('pain_relievers_to_avoid', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('other_medical_conditions', models.TextField(blank=True, default='')),
            ],
        ),
    ]
