# Generated by Django 5.0.7 on 2025-03-02 10:47

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preopassessment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='preopassessment',
            name='existing_conditions',
        ),
        migrations.RemoveField(
            model_name='preopassessment',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='preopassessment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='alcohol_consumption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='blood_clotting',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='cancer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='covid_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='date_of_operation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='dental_descriptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='diabetes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='effective_pain_relievers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='family_anaesthetic_reaction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='gastrointestinal_issues',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='heart_issues',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='hospital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='kidney_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='lung_issues',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='neurological_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='operation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='operation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='other_medical_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='pain_relievers_to_avoid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='previous_anaesthetic',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='recently_unwell',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='regular_medications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='rheumatoid_arthritis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='shortness_of_breath',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='smoke_or_vape',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='surgeon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='thyroid_disease',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preopassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='preopassessment',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='preopassessment',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
