# Generated by Django 5.2.5 on 2025-08-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_created_at_hospital_updated_at'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='hospital',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
