services:
  postgres:
    image: postgres:16
    container_name: easy-op-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: easy-op
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d easy-op"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # frontend:
  #   build:
  #     context: ./frontend/realty-reach/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - postgres

  # This currently needs to be run seperately as it doesn't wait long enough to startup
  # and hence the postgres server is not up and ready
  # backend:
  #   image: ${DOCKER_REGISTRY-}easy-op:api
  #   build:
  #     context: .
  #     dockerfile: easy-op/Dockerfile
  #   ports:
  #     - "8000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - postgres


volumes:
  postgres_data: