# Generated by Django 5.2.5 on 2025-10-26 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0004_alter_hospital_id'),
        ('patients', '0003_patient_ethnicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('side', models.TextField(blank=True, null=True)),
                ('indication', models.TextField()),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
