# Generated by Django 5.0.7 on 2025-07-14 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardiacAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('pre_op_assessment_id', models.CharField(max_length=255, unique=True)),
                ('colour', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('outcomes', models.CharField(max_length=255, null=True)),
                ('rcri_score', models.IntegerField(blank=True, null=True)),
                ('dasi_score', models.IntegerField(blank=True, null=True)),
                ('active_cardiac_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
            ],
        ),
    ]
