# Generated by Django 5.2.5 on 2025-09-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_response_updated_at_alter_form_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='yellow', max_length=20),
        ),
    ]
