# Generated by Django 5.2.5 on 2025-09-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_form_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='response',
        ),
        migrations.RemoveField(
            model_name='form',
            name='status',
        ),
    ]
