# Generated by Django 5.2.5 on 2025-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_form_response_remove_form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='yellow', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(default='yellow', max_length=20),
        ),
    ]
