# Generated by Django 5.2.5 on 2025-10-24 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_response_form_status_alter_response_status'),
        ('hospitals', '0004_alter_hospital_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('side', models.TextField(blank=True, null=True)),
                ('indication', models.TextField()),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='hospitals.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='form',
            name='surgery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='forms.surgery'),
        ),
    ]
