# Generated by Django 5.2.5 on 2025-10-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_surgery_form_surgery'),
        ('surgeries', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='surgery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='surgeries.surgery'),
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
    ]
